name: Template Cleanup
on: push

jobs:

    template-cleanup:
        name: Template Cleanup
        runs-on: ubuntu-latest
        if: github.event.repository.name != 'bundle-template' && github.ref_name == github.event.repository.default_branch
        permissions:
            contents: write
        steps:

            -   name: Generate app token
                id: generate_token
                uses: actions/create-github-app-token@v3
                with:
                    client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                    private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                    owner: ${{ github.repository_owner }}

            # Check out current repository
            -   name: Fetch Sources
                uses: actions/checkout@v7
                with:
                    token: ${{ steps.generate_token.outputs.token }}

            -   name: Setup PHP Action
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    coverage: none
                    extensions: pdo_sqlite, gd
                    tools: cs2pr

            -   name: Get bundle generator
                uses: actions/checkout@v7
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    repository: ibexa/bundle-generator
                    path: .generator

            -   name: "Install composer and dependencies"
                run: |
                    composer install -d .generator

            # Cleanup project
            -   name: Cleanup
                run: |
                    export LC_CTYPE=C
                    export LANG=C
                    # Prepare variables
                    NAME="${GITHUB_REPOSITORY##*/}"
                    PACKAGE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
                    
                    # Converts repository name to UpperCamelCase (if separated by "-")
                    _temp=(${NAME//-/ })
                    BUNDLE_NAME=$(printf %s "${_temp[@]^}")
                    
                    # Remove lines marked with #REMOVE-ON-CLEANUP#
                    find . -type f -not -path './.git/*' -not -path './.generator/*' -exec sed -i '/#REMOVE-ON-CLEANUP#/d' {} +
                    
                    # Run generator
                    echo Running generator with: php .generator/bin/ibexa-bundle-generator $PACKAGE_NAME $PACKAGE_NAME-dir --vendor-name=ibexa --vendor-namespace=Ibexa --bundle-name=$BUNDLE_NAME --skeleton-name=ibexa-oss
                    php .generator/bin/ibexa-bundle-generator $PACKAGE_NAME $PACKAGE_NAME-dir --vendor-name=ibexa --vendor-namespace=Ibexa --bundle-name=$BUNDLE_NAME --skeleton-name=ibexa-oss
                    
                    # Remove ibexa/bundle-template workflows 
                    rm -rf .github
                    
                    # Move content
                    cp -R $PACKAGE_NAME-dir/. .
                    
                    # Cleanup
                    rm -rf \
                      .github/workflows/template-cleanup.yml \
                      .generator \
                      $PACKAGE_NAME-dir
            # Commit modified files
            -   name: Commit files
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git add .
                    git commit -m "Template cleanup"
            # Push changes
            -   name: Push changes
                run: git push origin "HEAD:$GITHUB_REF_NAME"
